[package]
name = "cnctd_server"
version = "0.1.3"
edition = "2021"
authors = ["Connected Dot Inc.", "Kyle Ebner <kyle@cnctd.world>"]
description = "Collection of server APIs"
repository = "https://github.com/Connected-Dot/cnctd_server"
license = "MIT"
keywords = ["module"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
local-ip-address = "0.5.6"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
warp = "0.3.6"
