[package]
name = "cnctd_server"
version = "0.1.14"
edition = "2021"
authors = ["Connected Dot Inc.", "Kyle Ebner <kyle@cnctd.world>"]
description = "Collection of server APIs"
repository = "https://github.com/Connected-Dot/cnctd_server"
license = "MIT"
keywords = ["module"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
futures-util = "0.3.30"
local-ip-address = "0.5.6"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
tokio = { version = "1.35.1", features = ["full"] }
tokio-stream = "0.1.15"
warp = "0.3.6"
